# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 01:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_curso', models.CharField(max_length=200, verbose_name='nome do curso')),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_instituicao', models.CharField(max_length=200, verbose_name='nome da instituição')),
                ('sigla', models.CharField(max_length=20, verbose_name='sigla da instituição')),
                ('cidade', models.CharField(max_length=200, verbose_name='cidade da instituição')),
                ('nome_da_unidade', models.CharField(blank=True, max_length=200, verbose_name='nome da unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_pesquisador', models.CharField(max_length=200, unique=True, verbose_name='nome do pesquisador')),
                ('nome_cientifico', models.CharField(max_length=200, verbose_name='nome de referência científica do pesquisador')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='sexo do pesquisador')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail do pesquisador')),
                ('titulo', models.CharField(choices=[('graduando_bacharel', 'Graduando em Bacharelado'), ('graduando_licenciatura', 'Graduando em Licenciatura'), ('graduado_bacharel', 'Graduado em Bacharelado'), ('graduado_licenciatura', 'Graduado em Licenciatura'), ('especialita', 'Especialista'), ('mestre', 'Mestre'), ('doutor', 'Doutor')], max_length=100, verbose_name='título do pesquisador')),
                ('url_lates', models.CharField(blank=True, max_length=200, verbose_name='URL curriculo do LATES')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisador.Curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'pesquisadores',
                'verbose_name': 'pesquisador',
                'db_table': 'pesquisador',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisador.Instituicao'),
        ),
    ]
